BloggerBlogBundle_homepage:
    path:     /blog
    defaults: { _controller: BloggerBlogBundle:Blog:index }
    requirements:
      _method: GET

BloggerBlogBundle_blog_show:
    path:  /blog/{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+

BloggerBlogBundle_about:
    pattern:  /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        _method:  GET

BloggerBlogBundle_contact:
    pattern:  /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
        _method:  GET|POST