BloggerBlogBundle_homepage:
    path:     /blog
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
      _method: GET

blogger_blog_homepage:
    path:     /blog/{name}
    defaults: { _controller: BloggerBlogBundle:Page:index }
    requirements:
      _method: GET

BloggerBlogBundle_about:
    pattern:  /about
    defaults: { _controller: BloggerBlogBundle:Page:about }
    requirements:
        _method:  GET

BloggerBlogBundle_contact:
    pattern:  /contact
    defaults: { _controller: BloggerBlogBundle:Page:contact }
    requirements:
        _method:  GET|POST